	function randomFunne(){
		var funnes = 
		["help me",
     "i got bored",
     "bro",
     "bruh",
     "hello",
     "Have a nice day!",
     "that is one silly cat",
     "fatfatmillycat",
     "Saul Goodman",
     "You all know exactly who I am. Say my name…",
     "Club Penguin",
     "I used to rule the world..",
     "Chunks would load when I gave the word..",
     "Now every night I go stow away..",
     "Hide from the mobs I used to slay..",
     "They once were terrified..",
     "Every time I looked into their eyes..",
     "Villagers would cheer my way..",
     "For a hero I was, that's what they'd say",
     "One minute we had it all..",
     "Next our world began to fall..",
     "Away from all that it had once become..",
     "They all cried for my help, but I stood there numb..",
     "I gaze off into the boundless skyline..",
     "Note block choirs playing in the sunshine..",
     "Turn around, pick up my sword and wield..",
     "The blade that once forced evil mobs to yield..",
     "And hope one day that this chaos and..",
     "Destruction turns for the better..",
     "Never a bow in hand..",
     "That was when I ruled the land..",
     "If this battle should leave me slain..",
     "I know Herobrine will call my name..",
     "WTF",
     "I hate twitter",
     "💪",
     "Making websites takes so long",
     "💀",
     "D'oh!",
     "Hit the Pinata!",
     "If you don't wanna miss all the good stuff, you gotta get up before the sun does. Because the sun is a lazybones. Also breakfast is a part of a nutritious breakfast. -Probably the President",
     "Is this the Krusty Krab?",
     "No, this is Funne Co.",
     "Well, it may be stupid, but it's also dumb.",
     "abcdefghijklmnopqrstuvwxyz",
     "Error 404",
     "Unable to reach server: Error MARS",
     "Hacking...",
     "Your IP: 192.169.0.1",
     "Example",
     "Unable to connect to the Internet.",
     "Please try again later.",
     "Funne Co.",
     "Funne",
     "Uhhhhhhh",
		];
		var index = Math.floor(Math.random()*funnes.length);
		$("#random-funne").text(funnes[index]);
	}
    $(document).ready(function() {
		randomFunne();
    });
